name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
categories:
 #todo - add sections for PRs, no major, minor, patch
  - title: 'Other updates'
    labels:
      - 'documentation'
      - 'enhancement'
  - title: 'Bumps'
    labels:
      - 'bump'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: minor
template: |
  # Changes

  $CHANGES
